In [91]:
import numpy as np
import plotly.offline as pyo
import plotly.graph_objs as go
from scipy.spatial.distance import cdist

In [221]:
c1 = [[0,0],10]
c2 = [[8.,0],9]
c3 = [[3.,0],15]

In [288]:
gamma = 0.1

In [302]:
traces = []

trace = {
    'type':'scatter',
    'mode':'markers',
    'x':[c1[0][0],c2[0][0],c3[0][0]],
    'y':[c1[1],c2[1],c3[1]],
    'name':'observed points',
}

traces.append(trace)

fig = go.Figure(traces, layout)

pyo.iplot(fig)

In [290]:
def gauss_rbf(gamma, x, c):
    return np.exp(-gamma*(np.linalg.norm(x-c))**2)

In [291]:
def gauss_rbf_dist(gamma, dist):
    return np.exp(-gamma*(dist)**2)

In [303]:
x = np.linspace(-10.,20.,100)

traces = []

trace = {
    'type':'scatter',
    'mode':'markers',
    'x':[c1[0][0],c2[0][0],c3[0][0]],
    'y':[c1[1],c2[1],c3[1]],
    'name':'observed points',
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':[c1[1]*gauss_rbf(gamma,xi,c1[0][0]) for xi in x],
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':[c2[1]*gauss_rbf(gamma,xi,c2[0][0]) for xi in x],
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':[c3[1]*gauss_rbf(gamma,xi,c3[0][0]) for xi in x],
}

traces.append(trace)

layout = {
    'title':'rbf',
}

fig = go.Figure(traces, layout)

pyo.iplot(fig)

In [293]:
Y = cdist([c1[0],c2[0],c3[0]], [c1[0],c2[0],c3[0]], 'euclidean')

In [294]:
Y

array([[0., 8., 3.],
       [8., 0., 5.],
       [3., 5., 0.]])

In [295]:
Y_g = gauss_rbf_dist(gamma, Y)

In [296]:
Y_g

array([[1.        , 0.00166156, 0.40656966],
       [0.00166156, 1.        , 0.082085  ],
       [0.40656966, 0.082085  , 1.        ]])

In [297]:
Y_inv_g = np.linalg.inv(Y_g)

In [298]:
Y_inv_g

array([[ 1.19948855,  0.03829587, -0.49081917],
       [ 0.03829587,  1.00800632, -0.09831214],
       [-0.49081917, -0.09831214,  1.20762213]])

In [299]:
w = np.dot(Y_inv_g, np.array([c1[1],c2[1],c3[1]]))

In [300]:
w

array([ 4.97726083,  7.98033355, 12.32133109])

In [306]:
traces = []

trace = {
    'type':'scatter',
    'mode':'markers',
    'x':[c1[0][0],c2[0][0],c3[0][0]],
    'y':[c1[1],c2[1],c3[1]],
    'name':'observed points'
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':[w[0]*gauss_rbf(gamma,xi,c1[0][0]) for xi in x],
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':[w[1]*gauss_rbf(gamma,xi,c2[0][0]) for xi in x],
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':[w[2]*gauss_rbf(gamma,xi,c3[0][0]) for xi in x],
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':np.array([w[0]*gauss_rbf(gamma,xi,c1[0][0]) for xi in x]) + np.array([w[1]*gauss_rbf(gamma,xi,c2[0][0]) for xi in x]) + np.array([w[2]*gauss_rbf(gamma,xi,c3[0][0]) for xi in x]),
    'name':'linead combination of RBFs',
}

traces.append(trace)

layout = {
    'title':'rbf',
}

fig = go.Figure(traces, layout)

pyo.iplot(fig)

In [560]:
def sin_f(x):
    return np.sin(x)

In [561]:
def squared(x):
    return -3*(x**2)+100

In [562]:
x = np.linspace(-10,10,500)
x_ran = np.random.choice(x,100)

In [563]:
observed = [sin_f(xi) for xi in x_ran]

In [564]:
observed = [squared(xi) for xi in x_ran]

In [565]:
traces = []

trace = {
    'type':'scatter',
    'mode':'markers',
    'x':x_ran,
    'y':observed,
    'name':'observed points',
}

traces.append(trace)

fig = go.Figure(traces, layout)

pyo.iplot(fig)

In [566]:
coords = [list(a) for a in zip(x_ran, np.zeros(len(x_ran)))]

In [567]:
from sklearn.cluster import KMeans

In [601]:
def plot_inertia(coords, max_clus):
    inertia = []
    n_clus = np.arange(1,max_clus,1)
    for n in n_clus:
        kmeans = KMeans(n_clusters=n).fit(coords)
        inertia.append(kmeans.inertia_)
        
    traces = []
    
    trace = {
    'type':'scatter',
    'mode':'lines',
    'x':n_clus,
    'y':inertia,
    'name':'observed points',
    }
    
    traces.append(trace)
    
    layout = {
    'title':'inertia',
    }

    fig = go.Figure(traces, layout)

    pyo.iplot(fig)    

In [602]:
plot_inertia(coords, 6)

In [570]:
kmeans = KMeans(n_clusters=4).fit(coords)

In [571]:
traces = []

trace = {
    'type':'scatter',
    'mode':'markers',
    'x':x_ran,
    'y':np.zeros(len(x_ran)),
    'marker':{'color':kmeans.labels_},
    'name':'observed points',
}

traces.append(trace)

fig = go.Figure(traces, layout)

pyo.iplot(fig)

In [572]:
centers = kmeans.cluster_centers_

In [573]:
Y = cdist(coords, centers, 'euclidean')

In [574]:
Y_g = gauss_rbf_dist(gamma, Y)

In [575]:
Y_prod = np.dot(Y_g.T, Y_g)

In [576]:
Y_inv_prod = np.linalg.inv(Y_prod)

In [577]:
Y_inv_prod_transp = np.dot(Y_inv_prod, Y_g.T)

In [578]:
w = np.dot(Y_inv_prod_transp, observed)

In [579]:
gamma = 0.1

In [580]:
traces = []

trace = {
    'type':'scatter',
    'mode':'markers',
    'x':x_ran,
    'y':observed,
    'marker':{'color':kmeans.labels_},
    'name':'observed points',
}

traces.append(trace)

trace = {
    'type':'scatter',
    'mode':'markers',
    'x':[i[0] for i in centers],
    'y':[i[1] for i in centers],
    'name':'centers',
}

traces.append(trace)

sums = np.zeros(len(x))

for idx, w_value in enumerate(w):
    
    y = np.array([w_value * gauss_rbf(gamma, xi, centers[idx][0]) for xi in x])
    sums = sums + y
    
    trace = {
    'type':'scatter',
    'mode':'lines',
    'x':x,
    'y':y,
    }

    traces.append(trace)

trace = {
'type':'scatter',
'mode':'lines',
'x':x,
'y':sums,
'name':'combination'
}

traces.append(trace)

fig = go.Figure(traces, layout)

pyo.iplot(fig)

In [599]:
def pseudo_inverse(centers, coords, gamma_vec, observed):
    Y = cdist(coords, centers, 'euclidean')
    Y_squared = Y**2
    Y_gamma = Y*gamma_vec
    Y_exp = np.exp(Y_gamma)
    Y_transp_prod = np.dot(Y_exp.T, Y_exp)
    Y_inv_prod = np.linalg.inv(Y_transp_prod)
    Y_inv_prod_transp = np.dot(Y_inv_prod, Y_exp.T)
    w = np.dot(Y_inv_prod_transp, observed)
    return w

In [600]:
pseudo_inverse(centers, coords, np.array([[0.1,0.1,0.1,0.1]]), observed)

array([ 152.08746657, -216.63100605, -224.64747564,  151.74730633])